name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the Node version your project needs

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: 2/src

      # 4. Run tests
      - name: Run tests
        run: npm run test
        working-directory: 2/src
